const thirdPreviousDataSet = {
    "type": "FeatureCollection",
    "name": "tcdi_centroids",
    "features": [
        { "type": "Feature", "properties": { "FID": 263, "YR": 2010, "ID": 39, "PROJ_DESC": "This project will build upon the recommendations of the Township’s master plan and Browns Mills Strategic Revitalization Study to adopt a form-based code for the Town Center Zoning District and designated redevelopment areas in Browns Mills.", "AMT_WEB": "$28,400", "TITLE": "Town Center Redevelopment Plan", "WEBLINK": "na", "LAT": -74.58408714, "LONG": 39.97089468, "LEAD_MUN": "Pemberton Township" }, "geometry": { "type": "Point", "coordinates": [ -74.58408714, 39.97089468 ] } },
        { "type": "Feature", "properties": { "FID": 132, "YR": 2010, "ID": 34, "PROJ_DESC": "TCDI funds will be used to create a comprehensive revitalization plan by promoting land use, economic development, and marketing strategies.", "AMT_WEB": "$75,000", "TITLE": "Downtown Revitalization Plan and Marketing Study", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NcjJPUDEwRmhUZVE\/view?usp=drivesdk", "LAT": -75.13057632, "LONG": 39.73349597, "LEAD_MUN": "Pitman" }, "geometry": { "type": "Point", "coordinates": [ -75.13057632, 39.73349597 ] } },
        { "type": "Feature", "properties": { "FID": 133, "YR": 2010, "ID": 48, "PROJ_DESC": "This project will allow the Township to prepare a redevelopment plan for the Brunswick Pike corridor to convert a suburban corridor into a lively mixed-use district.", "AMT_WEB": "$55,000", "TITLE": "Brunswick Pike Redevelopment", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NTV9hNk1GOUFmZFk\/view?usp=drivesdk", "LAT": -74.72053149, "LONG": 40.29537644, "LEAD_MUN": "Lawrence Township" }, "geometry": { "type": "Point", "coordinates": [ -74.72053149, 40.29537644 ] } },
        { "type": "Feature", "properties": { "FID": 134, "YR": 2010, "ID": 37, "PROJ_DESC": "This project will provide for shared parking strategies for additional parking needs in the business district of the Township.", "AMT_WEB": "$50,000", "TITLE": "Main Street Town Center Parking Study", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NNTVSOS14ZHFDLUE\/view?usp=drivesdk", "LAT": -74.94119082, "LONG": 39.97844974, "LEAD_MUN": "Moorestown" }, "geometry": { "type": "Point", "coordinates": [ -74.94119082, 39.97844974 ] } },
        { "type": "Feature", "properties": { "FID": 135, "YR": 2010, "ID": 38, "PROJ_DESC": "TCDI funds will be used to produce a marketing and redevelopment plan for two important sites in downtown Mt. Holly.  These redevelopment studies are integral parts of the form-based code that will be adopted by the township.", "AMT_WEB": "$75,000", "TITLE": "Redevelopment Market and Feasibility", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NZDQ0NHdlMnd0Tjg\/view?usp=drivesdk", "LAT": -74.78629034, "LONG": 39.99499147, "LEAD_MUN": "Mt. Holly" }, "geometry": { "type": "Point", "coordinates": [ -74.78629034, 39.99499147 ] } },
        { "type": "Feature", "properties": { "FID": 136, "YR": 2010, "ID": 42, "PROJ_DESC": "The Borough will develop a form-based code to implement recommendations from the Master Plan reexamination.", "AMT_WEB": "$75,000", "TITLE": "Form Based Code", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NbG9lYUppME1fR0k\/view?usp=drivesdk", "LAT": -75.06450771, "LONG": 39.87912084, "LEAD_MUN": "Haddon Heights" }, "geometry": { "type": "Point", "coordinates": [ -75.06450771, 39.87912084 ] } },
        { "type": "Feature", "properties": { "FID": 137, "YR": 2010, "ID": 45, "PROJ_DESC": "The borough will develop a plan to promote safe pedestrian and vehicular traffic through the downtown to improve the climate for redevelopment.", "AMT_WEB": "$23,600", "TITLE": "Downtown Traffic Circulation and Parking Management", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NMm9GREE2N2F0X2s\/view?usp=drivesdk", "LAT": -75.14857442, "LONG": 39.79132296, "LEAD_MUN": "Wenonah" }, "geometry": { "type": "Point", "coordinates": [ -75.14857442, 39.79132296 ] } },
        { "type": "Feature", "properties": { "FID": 138, "YR": 2010, "ID": 40, "PROJ_DESC": "These funds will allow the city to develop an economic development strategy aimed at coordinating local priorities.  This study will establish an implementation timeline and responsibilities, sources of funding, and a prioritized list of projects.", "AMT_WEB": "$48,000", "TITLE": "CEDS", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NbnVST3hFRU44Z1E\/view?usp=drivesdk", "LAT": -75.10756319, "LONG": 39.93618305, "LEAD_MUN": "Camden City" }, "geometry": { "type": "Point", "coordinates": [ -75.10756319, 39.93618305 ] } },
        { "type": "Feature", "properties": { "FID": 139, "YR": 2010, "ID": 41, "PROJ_DESC": "The City of Camden will create an overlay district for the Broadway corridor from Martin Luther King Boulevard to Pine Street to provide a means of managing the form of new development, appropriate uses, and design guidelines.", "AMT_WEB": "$40,000", "TITLE": "Broadway Overlay District", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NdVNxYzBqNndqQ0k\/view?usp=drivesdk", "LAT": -75.10756319, "LONG": 39.93618305, "LEAD_MUN": "Camden City" }, "geometry": { "type": "Point", "coordinates": [ -75.10756319, 39.93618305 ] } },
        { "type": "Feature", "properties": { "FID": 140, "YR": 2010, "ID": 47, "PROJ_DESC": "East Windsor and Hightstown Borough will work cooperatively along Route 33 to review current zoning and land uses for the redevelopment of underutilized sites.", "AMT_WEB": "$100,000", "TITLE": "Route 33 Revitalization", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NTmpab1E4djJCUW8\/view?usp=drivesdk", "LAT": -74.52941795, "LONG": 40.26058796, "LEAD_MUN": "East Windsor" }, "geometry": { "type": "Point", "coordinates": [ -74.52941795, 40.26058796 ] } },
        { "type": "Feature", "properties": { "FID": 141, "YR": 2010, "ID": 44, "PROJ_DESC": "The Borough will study the feasibility of creating a new green square and performing arts center on a greyfield site within the downtown.  These new destinations will connect to Rowan Boulevard.", "AMT_WEB": "$50,000", "TITLE": "Design for Glassboro Town Center", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NVnFpVk5YYTJqNjg\/view?usp=drivesdk", "LAT": -75.11133348, "LONG": 39.70135866, "LEAD_MUN": "Glassboro" }, "geometry": { "type": "Point", "coordinates": [ -75.11133348, 39.70135866 ] } },
        { "type": "Feature", "properties": { "FID": 142, "YR": 2010, "ID": 49, "PROJ_DESC": "TCDI funds will be used to move forward recommendations from the Trenton Train Station Redevelopment Analysis by conducting detailed implementation plans for four different proposed projects.", "AMT_WEB": "$75,000", "TITLE": "Fostering TOD", "WEBLINK": "na", "LAT": -74.76413829000001, "LONG": 40.22368004, "LEAD_MUN": "Trenton" }, "geometry": { "type": "Point", "coordinates": [ -74.76413829, 40.22368004 ] } },
        { "type": "Feature", "properties": { "FID": 143, "YR": 2010, "ID": 43, "PROJ_DESC": "This project will enable a new coalition between Merchantville, Pennsauken and Camden to develop a joint strategic revitalization plan for the West Maple neighborhood.  The plan will identify the boundaries of the neighborhood, assets, challenges,", "PROJ_DESC2": "and provide a vision for revitalization.", "AMT_WEB": "$60,000", "TITLE": "West Maple Neighborhood Revitalization Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NU2pSNEN6VlJDMjg\/view?usp=drivesdk", "LAT": -75.07927858, "LONG": 39.9516437, "LEAD_MUN": "Merchantville (Multi-Municipal)" }, "geometry": { "type": "Point", "coordinates": [ -75.07927858, 39.9516437 ] } },
        { "type": "Feature", "properties": { "FID": 144, "YR": 2010, "ID": 36, "PROJ_DESC": "TCDI funds will be used to provide a redevelopment plan for the area near the new rail station that is proposed in Bordentown Township.", "AMT_WEB": "$75,000", "TITLE": "Train Station Redevelopment", "WEBLINK": "na", "LAT": -74.70984504, "LONG": 40.14205447, "LEAD_MUN": "Bordentown City" }, "geometry": { "type": "Point", "coordinates": [ -74.70984504, 40.14205447 ] } },
        { "type": "Feature", "properties": { "FID": 145, "YR": 2010, "ID": 46, "PROJ_DESC": "Several neighborhood conservation plans will be created for areas that may be affected by redevelopment.  The plans will identify land use patterns, existing conditions, and a vision", "AMT_WEB": "$70,000", "TITLE": "Nieghborhood Conservation Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NWVp4dlJ6Z2hoa28\/view?usp=drivesdk", "LAT": -75.15239898, "LONG": 39.83785499, "LEAD_MUN": "Woodbury City" }, "geometry": { "type": "Point", "coordinates": [ -75.15239898, 39.83785499 ] } },
        { "type": "Feature", "properties": { "FID": 146, "YR": 2010, "ID": 35, "PROJ_DESC": "This study will provide for community visioning for the potential station stops within Gloucester County associated with the PATCO transit extension plans.", "AMT_WEB": "$100,000", "TITLE": "SJ Transit Expansion Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NaWlaR0pNVXpjdjQ\/view?usp=drivesdk", "LAT": -75.14107871, "LONG": 39.71706878, "LEAD_MUN": "Gloucester County (Multi-Municipal)" }, "geometry": { "type": "Point", "coordinates": [ -75.14107871, 39.71706878 ] } },
        { "type": "Feature", "properties": { "FID": 147, "YR": 2010, "ID": 25, "PROJ_DESC": "This study is a multi-municipal effort to complement an economic development study for nine municipalities within the Coatesville region.  This study will analyze existing assets and constraints and provide recommendations for redevelopment sites and", "PROJ_DESC2": "zoning revisions.", "AMT_WEB": "$100,000", "TITLE": "Western Chester County Economic Development Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NOHEtbDVZVjN6Nzg\/view?usp=drivesdk", "LAT": -75.76180335, "LONG": 40.00139449, "LEAD_MUN": "Caln Township (Multi-Municipal)" }, "geometry": { "type": "Point", "coordinates": [ -75.76180335, 40.00139449 ] } },
        { "type": "Feature", "properties": { "FID": 148, "YR": 2010, "ID": 22, "PROJ_DESC": "TCDI funds will be used to study the feasibility of moving the Willow Grove train station from its current location.  The study feasibility analysis will include stakeholder involvement, preliminary engineering, market analysis, and", "PROJ_DESC2": "funding strategies.", "AMT_WEB": "$60,000", "TITLE": "Willow Grove Train Station", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NZGNYZTZNaWRuSzA\/view?usp=drivesdk", "LAT": -75.1020709, "LONG": 40.15719641, "LEAD_MUN": "Upper Moreland Township" }, "geometry": { "type": "Point", "coordinates": [ -75.1020709, 40.15719641 ] } },
        { "type": "Feature", "properties": { "FID": 149, "YR": 2010, "ID": 23, "PROJ_DESC": "This project will bridge a key gap in the East Cost Greenway in Pennsylvania by developing a master plan for greenways and shared bikeways along State Road in Bensalem.", "AMT_WEB": "$60,000", "TITLE": "East Coast Greenway", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NSmh5N25aREc4TDg\/view?usp=drivesdk", "LAT": -74.94326096, "LONG": 40.10867686, "LEAD_MUN": "Bensalem Township" }, "geometry": { "type": "Point", "coordinates": [ -74.94326096, 40.10867686 ] } },
        { "type": "Feature", "properties": { "FID": 150, "YR": 2010, "ID": 24, "PROJ_DESC": "TCDI funds will be used to develop a strategy to enhance and expand bicycle amenities and provide information to recreational users for existing trails in the boroughs of Bristol, Morrisville, New Hope, and Yardley.", "AMT_WEB": "$40,000", "TITLE": "Bicycle Strategy", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NbC1YOFI1eTQ5UEE\/view?usp=drivesdk", "LAT": -74.85095287, "LONG": 40.21662313, "LEAD_MUN": "New Hope Borough" }, "geometry": { "type": "Point", "coordinates": [ -74.85095287, 40.21662313 ] } },
        { "type": "Feature", "properties": { "FID": 151, "YR": 2010, "ID": 26, "PROJ_DESC": "This project will look at the feasibility of designing a sign system that introduces verbal (ADA) and nonverbal messages for visitors and residents to Phoenixville.", "AMT_WEB": "$8,000", "TITLE": "Wayfinding Study", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-Nelk1QXlBWWdDWW8\/view?usp=drivesdk", "LAT": -75.52006337, "LONG": 40.13588935, "LEAD_MUN": "Phoenixville" }, "geometry": { "type": "Point", "coordinates": [ -75.52006337, 40.13588935 ] } },
        { "type": "Feature", "properties": { "FID": 152, "YR": 2010, "ID": 27, "PROJ_DESC": "The Borough will undertake several tasks to complete the TRID three-phase process.  The borough will continue with outreach to stakeholders.", "AMT_WEB": "$50,000", "TITLE": "TRID", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NQnRzYndzTWJTZWc\/view?usp=drivesdk", "LAT": -75.41602376, "LONG": 39.81292864, "LEAD_MUN": "Marcus Hook" }, "geometry": { "type": "Point", "coordinates": [ -75.41602376, 39.81292864 ] } },
        { "type": "Feature", "properties": { "FID": 153, "YR": 2010, "ID": 28, "PROJ_DESC": "TCDI funds will provide the borough to create a TOD plan highlighting bicycle and pedestrian links, an official map, and market research to create an overlay zone near the train station.", "AMT_WEB": "$50,000", "TITLE": "Station Area TOD", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NZ2pMMXUzT0lqb28\/view?usp=drivesdk", "LAT": -75.25261624, "LONG": 39.96375825, "LEAD_MUN": "Millbourne" }, "geometry": { "type": "Point", "coordinates": [ -75.25261624, 39.96375825 ] } },
        { "type": "Feature", "properties": { "FID": 154, "YR": 2010, "ID": 29, "PROJ_DESC": "This study will complement ongoing economic and transportation investments to provide safe connections between the transportation center and downtown Norristown.", "AMT_WEB": "$45,000", "TITLE": "Streetscape Master Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NaVlSclUtRDVnZXc\/view?usp=drivesdk", "LAT": -75.33986062, "LONG": 40.122384, "LEAD_MUN": "Norristown" }, "geometry": { "type": "Point", "coordinates": [ -75.33986062, 40.122384 ] } },
        { "type": "Feature", "properties": { "FID": 155, "YR": 2010, "ID": 30, "PROJ_DESC": "The High Street Corridor plan is a cooperative effort from Pottstown Borough and West Pottsgrove Township.  The study will focus on implementation goals to revitalize the entire corridor.", "AMT_WEB": "$65,000", "TITLE": "High Street Corridor", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-NU04xV0lJdXVfTDQ\/view?usp=drivesdk", "LAT": -75.65380913, "LONG": 40.25347504, "LEAD_MUN": "Pottstown  (Multi-Municipal)" }, "geometry": { "type": "Point", "coordinates": [ -75.65380913, 40.25347504 ] } },
        { "type": "Feature", "properties": { "FID": 156, "YR": 2010, "ID": 33, "PROJ_DESC": "TCDI funds will be used to support the urban design and physical planning aspects of the Comprehensive Plan.  Staff will prepare design concepts and plan recommendations for the city-wide long range plan and District Plans.", "AMT_WEB": "$60,000", "TITLE": "Urban Design", "WEBLINK": "na", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } },
        { "type": "Feature", "properties": { "FID": 157, "YR": 2010, "ID": 32, "PROJ_DESC": "The handbook will provide a single guide to roadway design, curb cuts, extensions, and transit supportive design and parking for development within the City of Philadelphia.", "AMT_WEB": "$86,000", "TITLE": "Complete Streets", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0B6gfXHKohx-Nb29wQjBkMzE0bm8\/view?usp=drivesdk", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } },
        { "type": "Feature", "properties": { "FID": 158, "YR": 2010, "ID": 31, "PROJ_DESC": "This project will develop recommendations for improvements to the bicycle and pedestrian networks in West and Southwest Philadelphia.", "AMT_WEB": "$62,000", "TITLE": "Pedestrian and Bicycle Plan", "WEBLINK": "na", "LAT": -75.22535062, "LONG": 39.94158378, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.22535062, 39.94158378 ] } }
    ]
}
const secondPreviousDataSet = {
    "type": "FeatureCollection",
    "name": "tcdi_centroids",
    "features": [
        { "type": "Feature", "properties": { "FID": 159, "YR": 2012, "ID": 207, "PROJ_DESC": "The purpose of the Revitalization and Visioning plan is to develop a planning tool that all stakeholders can utilize to help guide future business and community development.", "AMT_WEB": "$12,000", "TITLE": "Visioning", "WEBLINK": "na", "LAT": -75.20366996, "LONG": 40.37287509, "LEAD_MUN": "Dublin Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.20366996, 40.37287509 ] } },
        { "type": "Feature", "properties": { "FID": 160, "YR": 2012, "ID": 244, "PROJ_DESC": "This project will involve the development of a borough-wide comprehensive plan that includes economic development, circulation, multi modal transportation options, and implementation.", "AMT_WEB": "$40,000", "TITLE": "Town Center Development Plan", "WEBLINK": "na", "LAT": -75.2919878, "LONG": 40.37217603, "LEAD_MUN": "Perkasie" }, "geometry": { "type": "Point", "coordinates": [ -75.2919878, 40.37217603 ] } },
        { "type": "Feature", "properties": { "FID": 161, "YR": 2012, "ID": 245, "PROJ_DESC": "This project will explore solutions for providing diverse housing options within Chester County.  It will take a multi-municipal approach and will assess the housing situation of low-wage workers, where they work, and", "PROJ_DESC2": "how they get from home to places of employment.  The study will include a specific focus on reinvestment in the four boroughs - Kennett Square, Avondale, West Grove, and Oxford - within the study area, and", "PROJ_DESC3": "will result in a strategy for better coordination of transportation and affordable housing.  The study strives to foster public\/private partnerships that will be designed to continue through the implementation phase of the project.", "AMT_WEB": "$86,800", "TITLE": "Route 1 Housing Affordability Study", "WEBLINK": "na", "LAT": -75.86363371, "LONG": 39.8108261, "LEAD_MUN": "Chester County" }, "geometry": { "type": "Point", "coordinates": [ -75.86363371, 39.8108261 ] } },
        { "type": "Feature", "properties": { "FID": 162, "YR": 2012, "ID": 247, "PROJ_DESC": "The purpose of this project is to prepare a new zoning ordinance to implement the recommendations of the Comprehensive Plan Update adopted earlier this year. This plan recommends the development of a new zoning ordinance, including elements of a", "PROJ_DESC2": "form-based code.", "AMT_WEB": "$90,000", "TITLE": "Zoning Code Update", "WEBLINK": "na", "LAT": -75.52006337, "LONG": 40.13588935, "LEAD_MUN": "Phoenixville" }, "geometry": { "type": "Point", "coordinates": [ -75.52006337, 40.13588935 ] } },
        { "type": "Feature", "properties": { "FID": 163, "YR": 2012, "ID": 248, "PROJ_DESC": "This project will utilize the assistance of a consulting team to analyze ways to consolidate and modernize the commercial zoning districts within the Township.", "AMT_WEB": "$50,000", "TITLE": "Commercial Zoning", "WEBLINK": "na", "LAT": -75.45400165, "LONG": 40.0663081, "LEAD_MUN": "Tredyffrin Township" }, "geometry": { "type": "Point", "coordinates": [ -75.45400165, 40.0663081 ] } },
        { "type": "Feature", "properties": { "FID": 164, "YR": 2012, "ID": 250, "PROJ_DESC": "This project will focus on a visioning and planning process that will result in a revised subdivision and land use ordinance appropriate to Media’s size and urban qualities and a revised building code that will promote green building practices and", "PROJ_DESC2": "energy efficient structures.", "AMT_WEB": "$36,500", "TITLE": "Comprehensive Plan", "WEBLINK": "na", "LAT": -75.38897621, "LONG": 39.91975519, "LEAD_MUN": "Media Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.38897621, 39.91975519 ] } },
        { "type": "Feature", "properties": { "FID": 165, "YR": 2012, "ID": 251, "PROJ_DESC": "TCDI funds will be used to synthesize recommendations of past studies into a Pedestrian and Bicycle Accessibility Master Plan.", "AMT_WEB": "$20,000", "TITLE": "Bike and Ped Plan", "WEBLINK": "na", "LAT": -75.34872172, "LONG": 39.90231021, "LEAD_MUN": "Swarthmore Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.34872172, 39.90231021 ] } },
        { "type": "Feature", "properties": { "FID": 166, "YR": 2012, "ID": 253, "PROJ_DESC": "TCDI funds will be used to undergo the TRID Planning Study, together with the active involvement and participation of the Montgomery County Planning Commission and SEPTA.", "AMT_WEB": "$60,000", "TITLE": "TRID", "WEBLINK": "na", "LAT": -75.11456772, "LONG": 40.11080415, "LEAD_MUN": "Abington Township" }, "geometry": { "type": "Point", "coordinates": [ -75.11456772, 40.11080415 ] } },
        { "type": "Feature", "properties": { "FID": 167, "YR": 2012, "ID": 254, "PROJ_DESC": "This project will utilize TCDI funds to improve existing infrastructure and attract residents and visitors by providing visible, aesthetic signage at strategic locations in the Borough.  The project will enhance infrastructure improvements to increase", "PROJ_DESC2": "the quality of life and support economic development.", "AMT_WEB": "$40,000", "TITLE": "Wayfinding", "WEBLINK": "na", "LAT": -75.28119889, "LONG": 40.24164092, "LEAD_MUN": "Lansdale Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.28119889, 40.24164092 ] } },
        { "type": "Feature", "properties": { "FID": 168, "YR": 2012, "ID": 257, "PROJ_DESC": "TCDI funds will be used to study the feasibility of creating a BID within the Borough.", "AMT_WEB": "$25,000", "TITLE": "Souderton BID", "WEBLINK": "na", "LAT": -75.32233152000001, "LONG": 40.31099641, "LEAD_MUN": "Souderton" }, "geometry": { "type": "Point", "coordinates": [ -75.32233152, 40.31099641 ] } },
        { "type": "Feature", "properties": { "FID": 169, "YR": 2012, "ID": 221, "PROJ_DESC": "TCDI funds will be used to develop a concept for pedestrian connections and gateways connecting the transportation center and courthouse complex.", "AMT_WEB": "$60,000", "TITLE": "TOD Marketing", "WEBLINK": "na", "LAT": -75.33986062, "LONG": 40.122384, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.33986062, 40.122384 ] } },
        { "type": "Feature", "properties": { "FID": 170, "YR": 2012, "ID": 223, "PROJ_DESC": "This project will provide UDT to create a unique “Transfer of Development Rights” ordinance, where existing development within the floodplain can be eliminated and those development rights can be transferred to higher, drier portions of the office pa", "PROJ_DESC2": "where new, mixed use development will be encouraged.", "AMT_WEB": "$25,000", "TITLE": "TDR for Ft. Washington", "WEBLINK": "na", "LAT": -75.1812935, "LONG": 40.15017338, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.1812935, 40.15017338 ] } },
        { "type": "Feature", "properties": { "FID": 171, "YR": 2012, "ID": 243, "PROJ_DESC": "TCDI funds will be used to develop preliminary design concepts for mobility improvements with the Hulmeville and Bellevue Avenue intersection striving to create a safer pedestrian and bicycle environment.", "AMT_WEB": "$20,000", "TITLE": "Multi Modal Improvements", "WEBLINK": "na", "LAT": -74.91455513, "LONG": 40.15529685, "LEAD_MUN": "Penndel Borough" }, "geometry": { "type": "Point", "coordinates": [ -74.91455513, 40.15529685 ] } },
        { "type": "Feature", "properties": { "FID": 172, "YR": 2012, "ID": 255, "PROJ_DESC": "This study will enable the Township and City Avenue Special Services District to expand on the transportation improvements previously proposed and to identify pedestrian pathways and connections to make transit, bus, and rail more", "PROJ_DESC2": "accessible and identifiable.", "AMT_WEB": "$50,000", "TITLE": "Pedestrian Connection for City Ave", "WEBLINK": "na", "LAT": -75.28072621, "LONG": 40.02823209, "LEAD_MUN": "Lower Merion" }, "geometry": { "type": "Point", "coordinates": [ -75.28072621, 40.02823209 ] } },
        { "type": "Feature", "properties": { "FID": 173, "YR": 2012, "ID": 249, "PROJ_DESC": "TCDI funds will be used to renew the pedestrian network of the CBD by having extensive an public outreach and visioning process and developing design schemes and technical features.", "AMT_WEB": "$30,700", "TITLE": "Downtown Pedestrian Connections", "WEBLINK": "na", "LAT": -75.27603644, "LONG": 39.94077234, "LEAD_MUN": "Lansdowne Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.27603644, 39.94077234 ] } },
        { "type": "Feature", "properties": { "FID": 174, "YR": 2012, "ID": 252, "PROJ_DESC": "TCDI funds will be used for planning activities along West Chester Pike such as traffic flow and parking, streetscaping and preliminary design of gateway improvements and ways to retain and attract business to the area.", "AMT_WEB": "$71,000", "TITLE": "West Chester Pike Traffic Study", "WEBLINK": "na", "LAT": -75.2895921, "LONG": 39.9499248, "LEAD_MUN": "Upper Darby Township" }, "geometry": { "type": "Point", "coordinates": [ -75.2895921, 39.9499248 ] } },
        { "type": "Feature", "properties": { "FID": 175, "YR": 2012, "ID": 224, "PROJ_DESC": "This study will evaluate whether a Road Diet is feasible for both First Avenue and Moore Road in King of Prussia.", "AMT_WEB": "$25,000", "TITLE": "Moore Road & 1st Avenue Road Diet", "WEBLINK": "na", "LAT": -75.37915826, "LONG": 40.09030244, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.37915826, 40.09030244 ] } },
        { "type": "Feature", "properties": { "FID": 176, "YR": 2012, "ID": 246, "PROJ_DESC": "The Borough of Malvern proposes to develop a transit development (TOD) plan for the area within a quarter mile of the Malvern SEPTA regional rail train station.  This plan will focus on applying higher densities for redevelopment of properties located", "PROJ_DESC2": "north of the train station, as well as include some analysis on properties located to the south for a future study.", "AMT_WEB": "$64,000", "TITLE": "Malvern TOD", "WEBLINK": "na", "LAT": -75.51442522000001, "LONG": 40.03291111, "LEAD_MUN": "Malvern Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.51442522, 40.03291111 ] } },
        { "type": "Feature", "properties": { "FID": 177, "YR": 2012, "ID": 226, "PROJ_DESC": "TCDI funds will support the PCPC District Planning and Zoning Map Revision Program during 2012 and 2013, as well as any technical subject or site-specific follow-up studies needed to complete or supplement the District Plans.", "AMT_WEB": "$100,000", "TITLE": "2035 District Plan and Zoning Revisions", "WEBLINK": "na", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } },
        { "type": "Feature", "properties": { "FID": 178, "YR": 2012, "ID": 281, "PROJ_DESC": "This project will allow for the City to develop a new zoning ordinance that matches the recommendations put forth in the new master plan.", "AMT_WEB": "$64,000", "TITLE": "Zoning Update", "WEBLINK": "na", "LAT": -74.8523867, "LONG": 40.07848669, "LEAD_MUN": "Burlington City" }, "geometry": { "type": "Point", "coordinates": [ -74.8523867, 40.07848669 ] } },
        { "type": "Feature", "properties": { "FID": 179, "YR": 2012, "ID": 282, "PROJ_DESC": "TCDI funds will be used to update the Township’s Master Plan by developing a Circulation Plan Element.", "AMT_WEB": "$50,000", "TITLE": "Circulation Element", "WEBLINK": "na", "LAT": -74.71493153, "LONG": 40.08538245, "LEAD_MUN": "Mansfield Township" }, "geometry": { "type": "Point", "coordinates": [ -74.71493153, 40.08538245 ] } },
        { "type": "Feature", "properties": { "FID": 180, "YR": 2012, "ID": 302, "PROJ_DESC": "TCDI funds will be used to program in exploring traffic calming measures to address heavy and fast moving traffic along Broad Street (County Route 543), from the border of Riverton to New Jersey State Highway 73.", "AMT_WEB": "$32,000", "TITLE": "Traffic Calming", "WEBLINK": "na", "LAT": -75.03628546, "LONG": 40.00266875, "LEAD_MUN": "Palmyra" }, "geometry": { "type": "Point", "coordinates": [ -75.03628546, 40.00266875 ] } },
        { "type": "Feature", "properties": { "FID": 181, "YR": 2012, "ID": 303, "PROJ_DESC": "TCDI funds will be used to develop a new bikeway plan within the Township that will connect to the Rancocas Greenway.", "AMT_WEB": "$32,000", "TITLE": "Bikeway Plan", "WEBLINK": "na", "LAT": -74.90469519, "LONG": 39.94836316, "LEAD_MUN": "Mt. Laurel" }, "geometry": { "type": "Point", "coordinates": [ -74.90469519, 39.94836316 ] } },
        { "type": "Feature", "properties": { "FID": 182, "YR": 2012, "ID": 304, "PROJ_DESC": "The Haddon Avenue Transit Village (HATV) is a planned mixed-use transit-oriented development situated between Our Lady of Lourdes Medical Center and the Ferry Avenue PATCO station. The requested TCDI funding will be utilized for", "PROJ_DESC2": "preliminary engineering of necessary roadway improvements for the site’s redevelopment.", "AMT_WEB": "$50,000", "TITLE": "Haddon Avenue Transit Corridor", "WEBLINK": "na", "LAT": -75.10756319, "LONG": 39.93618305, "LEAD_MUN": "Camden City" }, "geometry": { "type": "Point", "coordinates": [ -75.10756319, 39.93618305 ] } },
        { "type": "Feature", "properties": { "FID": 183, "YR": 2012, "ID": 308, "PROJ_DESC": "TCDI funds will be used to continue work from Phase I.   The multi-jurisdictional task force will strive to build upon Phase I recommendations and enhance the community capacity of the neighborhood.", "AMT_WEB": "$40,000", "TITLE": "West Maple Neighborhood Revitalization Plan - Phase 2", "WEBLINK": "na", "LAT": -75.05033881, "LONG": 39.95023155, "LEAD_MUN": "Merchantville Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.05033881, 39.95023155 ] } },
        { "type": "Feature", "properties": { "FID": 184, "YR": 2012, "ID": 309, "PROJ_DESC": "The purpose of this project is to encourage and guide the revitalization of the Bradlees site and to foster mutually beneficial relationships with stakeholders in order to improve land use and transportation connectivity.", "AMT_WEB": "$40,000", "TITLE": "Revitalization Plan for Bradlees Site", "WEBLINK": "na", "LAT": -75.01547967, "LONG": 39.82898996, "LEAD_MUN": "Stratford" }, "geometry": { "type": "Point", "coordinates": [ -75.01547967, 39.82898996 ] } },
        { "type": "Feature", "properties": { "FID": 185, "YR": 2012, "ID": 310, "PROJ_DESC": "The purpose of the project is to connect the newly redeveloped Voorhees Town Center to the proposed Voorhees Environmental Park on Centennial Blvd. so the two are linked to existing and proposed bicycle facilities.", "AMT_WEB": "$66,000", "TITLE": "Bikeway Plan", "WEBLINK": "na", "LAT": -74.95487835, "LONG": 39.84502051, "LEAD_MUN": "Voorhees" }, "geometry": { "type": "Point", "coordinates": [ -74.95487835, 39.84502051 ] } },
        { "type": "Feature", "properties": { "FID": 186, "YR": 2012, "ID": 306, "PROJ_DESC": "TCDI funds would be used to draft a form-based or hybrid code to create a TOD overlay zone that focuses on the Garden State Park stop of the NJ Transit Atlantic City Rail Line.", "AMT_WEB": "$60,000", "TITLE": "TOD Overlay", "WEBLINK": "na", "LAT": -74.99461206, "LONG": 39.90340864, "LEAD_MUN": "Cherry Hill" }, "geometry": { "type": "Point", "coordinates": [ -74.99461206, 39.90340864 ] } },
        { "type": "Feature", "properties": { "FID": 187, "YR": 2012, "ID": 307, "PROJ_DESC": "Funds will be used to conduct preliminary design on a streetscape plan serving the Blackwood West Community.", "AMT_WEB": "$50,000", "TITLE": "Blackwood Streetscape", "WEBLINK": "na", "LAT": -75.03630565, "LONG": 39.79241296, "LEAD_MUN": "Gloucester Township" }, "geometry": { "type": "Point", "coordinates": [ -75.03630565, 39.79241296 ] } },
        { "type": "Feature", "properties": { "FID": 188, "YR": 2012, "ID": 311, "PROJ_DESC": "TCDI funds will be used to create and implement an extensive strategic marketing plan for the revitalization of the Borough.", "AMT_WEB": "$50,000", "TITLE": "Marketing Plan", "WEBLINK": "na", "LAT": -75.31178198000001, "LONG": 39.74580602, "LEAD_MUN": "Swedesboro" }, "geometry": { "type": "Point", "coordinates": [ -75.31178198, 39.74580602 ] } },
        { "type": "Feature", "properties": { "FID": 189, "YR": 2012, "ID": 315, "PROJ_DESC": "The purpose of this project is to develop a concept plan for re-use of particular sites which maximizes its potential as a viable commercial area which will be within walking and biking distance to many residents.", "AMT_WEB": "$30,000", "TITLE": "Route 31 Corridor Redevelopment", "WEBLINK": "na", "LAT": -74.79074516, "LONG": 40.32624607, "LEAD_MUN": "Pennington" }, "geometry": { "type": "Point", "coordinates": [ -74.79074516, 40.32624607 ] } },
        { "type": "Feature", "properties": { "FID": 190, "YR": 2012, "ID": 313, "PROJ_DESC": "TCDI funds will be used to explore the needs for developing a link over I-95 for the Johnson Trolley Line.", "AMT_WEB": "$45,000", "TITLE": "Johnson Trolley Line Missing Link", "WEBLINK": "na", "LAT": -74.72053149, "LONG": 40.29537644, "LEAD_MUN": "Lawrence Township" }, "geometry": { "type": "Point", "coordinates": [ -74.72053149, 40.29537644 ] } },
        { "type": "Feature", "properties": { "FID": 191, "YR": 2012, "ID": 312, "PROJ_DESC": "The purpose of this project is to study various land uses and potential development around the newly developed Interchange 8 of the NJ Turnpike.", "AMT_WEB": "$100,000", "TITLE": "NJ Turnpike Development Sudy", "WEBLINK": "na", "LAT": -74.52941795, "LONG": 40.26058796, "LEAD_MUN": "East Windsor" }, "geometry": { "type": "Point", "coordinates": [ -74.52941795, 40.26058796 ] } },
        { "type": "Feature", "properties": { "FID": 192, "YR": 2012, "ID": 314, "PROJ_DESC": "TCDI funds would be used to support concept development and feasibility assessment for significant transportation infrastructure improvements necessary or desirable to improve redevelopment capacity and marketability of the potential Ewing Town Center.", "AMT_WEB": "$100,000", "TITLE": "Ewing Town Center", "WEBLINK": "na", "LAT": -74.80055576, "LONG": 40.26502543, "LEAD_MUN": "Mercer County" }, "geometry": { "type": "Point", "coordinates": [ -74.80055576, 40.26502543 ] } },
        { "type": "Feature", "properties": { "FID": 193, "YR": 2012, "ID": 305, "PROJ_DESC": "TCDI funds will be used to complete a new land use element and marketing piece for the updated Camden County Comprehensive Plan.", "AMT_WEB": "$150,000", "TITLE": "Land Use Element\/Summary Brief", "WEBLINK": "na", "LAT": -74.95990899, "LONG": 39.8036736, "LEAD_MUN": "Camden County" }, "geometry": { "type": "Point", "coordinates": [ -74.95990899, 39.8036736 ] } },
        { "type": "Feature", "properties": { "FID": 194, "YR": 2012, "ID": 229, "PROJ_DESC": "This study will improve roadway safety and functionality for pedestrians, cyclists, passenger vehicles, buses and trucks on Washington Avenue.  The study will also clarify parking and loading areas, look at landscaping and other streetscape improvements,", "PROJ_DESC2": "and take into consideration and recommend land use changes along Washington Avenue.  The goal of the project is to develop a plan for Washington Avenue as a Complete Street that works.", "AMT_WEB": "$75,000", "TITLE": "Washington Avenue Streetscape and Design", "WEBLINK": "na", "LAT": -75.165404, "LONG": 39.93722891, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.165404, 39.93722891 ] } },
        { "type": "Feature", "properties": { "FID": 195, "YR": 2012, "ID": 227, "PROJ_DESC": "The project is part of a larger initiative to design, test and build a cycle track along JFK Boulevard and Market Street, from Center City to 30th Street station. The Center City District has been studying the feasibility of building such a", "PROJ_DESC2": "cycle track since 2009.  This study will build upon the work of these conceptual studies and provide analysis for the western portion of the proposed cycle track. Completing this study will enable the City and the CCD to develop", "PROJ_DESC3": "preliminary engineering for the cycle track.", "AMT_WEB": "$76,000", "TITLE": "Center City Cycle Track Signal Timing", "WEBLINK": "na", "LAT": -75.1730675, "LONG": 39.95407961, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.1730675, 39.95407961 ] } },
        { "type": "Feature", "properties": { "FID": 196, "YR": 2012, "ID": 228, "PROJ_DESC": "This study will examine the potential of transit-oriented development and how it may best alter life in East Kensington. The study will involve some reflection on how East Kensington’s dynamic energy connects with the City of Philadelphia as a whole an", "PROJ_DESC2": "will include a review of current land uses.  The plan will establish a set of land use recommendations in anticipation of the impending zoning remapping and PCPC’s district planning.", "AMT_WEB": "$30,000", "TITLE": "East Kensington Community Development Plan", "WEBLINK": "na", "LAT": -75.12751788, "LONG": 39.98446514, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.12751788, 39.98446514 ] } },
        { "type": "Feature", "properties": { "FID": 264, "YR": 2012, "ID": 241, "PROJ_DESC": "This project will develop a revitalization plan for the Borough that focuses on maximizing the potential of the train station and North Main Street area for transit-oriented development and increased business activity.", "AMT_WEB": "$75,000", "TITLE": "Chalfont Borough Revitalization Project", "WEBLINK": "na", "LAT": -75.21026647, "LONG": 40.28803303, "LEAD_MUN": "Chalfont Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.21026647, 40.28803303 ] } },
        { "type": "Feature", "properties": { "FID": 265, "YR": 2012, "ID": 225, "PROJ_DESC": "The purpose of this program is to create a stronger sense of place in Willow Grove and help visitors to take advantage of the significant community and retail assets of the area. Elements include gateway improvement, interpretive signage, and wayfinding.", "AMT_WEB": "$38,000", "TITLE": "Willow Grove Placemaking", "WEBLINK": "na", "LAT": -75.1169651, "LONG": 40.15171495, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.1169651, 40.15171495 ] } }
    ]
}
const previousDataSet = {
    "type": "FeatureCollection",
    "name": "tcdi_centroids",
    "features": [
        { "type": "Feature", "properties": { "FID": 197, "YR": 2015, "ID": 441, "PROJ_DESC": "Create a multi-modal transportation system master plan that connects the major community elements, including the public schools, recreation facilities, New Jersey Transit locations, community center and points of interest with the regional pedestrian", "PROJ_DESC2": "and bikeway system.", "AMT_WEB": "$85,000", "TITLE": "Multi Modal Transportation System Master Plan", "WEBLINK": "na", "LAT": -74.9720192, "LONG": 39.65991417, "LEAD_MUN": "Monroe Township" }, "geometry": { "type": "Point", "coordinates": [ -74.9720192, 39.65991417 ] } },
        { "type": "Feature", "properties": { "FID": 198, "YR": 2015, "ID": 404, "PROJ_DESC": "Establish new land use regulations that address infill development within Whitemarsh Borough’s new Riverfront Overlay District.", "AMT_WEB": "$48,000", "TITLE": "Riverfront Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nWWgzQnd1T05PalE\/view?usp=drivesdk", "LAT": -75.25177158, "LONG": 40.10245076, "LEAD_MUN": "Whitemarsh" }, "geometry": { "type": "Point", "coordinates": [ -75.25177158, 40.10245076 ] } },
        { "type": "Feature", "properties": { "FID": 199, "YR": 2015, "ID": 383, "PROJ_DESC": "Create a Master Bicycle Plan to link the individual communities and various points of interest within the Township. It will consist of roadway bicycle lanes, shared lanes, side-paths, and multi-use trails through township parks and link with bicycle", "PROJ_DESC2": "resources in adjoining communities.", "AMT_WEB": "$60,000", "TITLE": "Master Bicycle Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16ndkV3TFgyRVFVMFE\/view?usp=drivesdk", "LAT": -75.11456772, "LONG": 40.11080415, "LEAD_MUN": "Abington Township" }, "geometry": { "type": "Point", "coordinates": [ -75.11456772, 40.11080415 ] } },
        { "type": "Feature", "properties": { "FID": 200, "YR": 2015, "ID": 417, "PROJ_DESC": "The Downtown Parking Plan is crucial for the redevelopment effort in Trenton. Identifying the necessary partners and creating an effective approach for managing parking will enhance downtown for pedestrians and motorists alike. TCDI funds will be", "PROJ_DESC2": "used to develop an updated Parking Plan to make Downtown Trenton more attractive for developers.", "AMT_WEB": "$100,000", "TITLE": "Trenton250-Downtown Planning District Parking Plan", "WEBLINK": "na", "LAT": -74.76413829000001, "LONG": 40.22368004, "LEAD_MUN": "Trenton" }, "geometry": { "type": "Point", "coordinates": [ -74.76413829, 40.22368004 ] } },
        { "type": "Feature", "properties": { "FID": 201, "YR": 2015, "ID": 362, "PROJ_DESC": "Evaluate the feasibility of transit-oriented and mixed use redevelopment opportunities for the area bound by I-95 to the west, the Delaware River to the east, Dunksferry Road to the north and Station Avenue\/Gravel Pike to the South.", "AMT_WEB": "$100,000", "TITLE": "Bensalem Riverfont Master Plan Evaluation and Implementation Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16ncWRONmZuLUNLRHM\/view?usp=drivesdk", "LAT": -74.94326096, "LONG": 40.10867686, "LEAD_MUN": "Bensalem Township" }, "geometry": { "type": "Point", "coordinates": [ -74.94326096, 40.10867686 ] } },
        { "type": "Feature", "properties": { "FID": 202, "YR": 2015, "ID": 401, "PROJ_DESC": "Develop a conceptual streetscape plan for the downtown historic Bethayres corridor, stretching along Huntingdon Pike from the Bethayres SEPTA train station up to the Bryn Athyn community at Buck Road.", "AMT_WEB": "$20,000", "TITLE": "Historic Bethayres Streetscape Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nclBZdkExZ2lkbkU\/view?usp=drivesdk", "LAT": -75.05418384, "LONG": 40.13457285, "LEAD_MUN": "Lower Moreland" }, "geometry": { "type": "Point", "coordinates": [ -75.05418384, 40.13457285 ] } },
        { "type": "Feature", "properties": { "FID": 203, "YR": 2015, "ID": 408, "PROJ_DESC": "To help spur the revitalization of the Wrightstown area, TCDI funds will be used to conduct a redevelopment plan to evaluate future land uses, transportation infrastructure improvements, and building and development standards.", "AMT_WEB": "$50,000", "TITLE": "Wrightstown Cookstown Redevelopment Plan", "WEBLINK": "na", "LAT": -74.57407537, "LONG": 40.01587663, "LEAD_MUN": "New Hanover Twp" }, "geometry": { "type": "Point", "coordinates": [ -74.57407537, 40.01587663 ] } },
        { "type": "Feature", "properties": { "FID": 204, "YR": 2015, "ID": 413, "PROJ_DESC": "Conduct a Feasibility Assessment to evaluate and analyze the potential of the proposed conversion of Market, Federal and Fifth Streets from one-way to two-way streets.  It will review the traffic efficiency and orientation of these major corridors,", "PROJ_DESC2": "pedestrian and bicycle safety, and effect of traffic direction on business visibility and accessibility.", "AMT_WEB": "$60,000", "TITLE": "Downtown Corridors Traffic Feasibility Study", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nUXRNc0hUY1VSUkk\/view?usp=drivesdk", "LAT": -75.10756319, "LONG": 39.93618305, "LEAD_MUN": "Camden City" }, "geometry": { "type": "Point", "coordinates": [ -75.10756319, 39.93618305 ] } },
        { "type": "Feature", "properties": { "FID": 205, "YR": 2015, "ID": 415, "PROJ_DESC": "The Town Centre East area has several challenges, including an awkward triangular shape, long-standing vacant structures, an ill-configured surface parking lot, a narrow adjacent street with very limited on-street parking opportunities, and", "PROJ_DESC2": "environmental contamination issues.  An updated redevelopment plan will be prepared address these issues.", "AMT_WEB": "$35,000", "TITLE": "Town Centre East Redevelopment Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nNk4zWGFmTHlkbE0\/view?usp=drivesdk", "LAT": -75.05033881, "LONG": 39.95023155, "LEAD_MUN": "Merchantville Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.05033881, 39.95023155 ] } },
        { "type": "Feature", "properties": { "FID": 206, "YR": 2015, "ID": 412, "PROJ_DESC": "Conduct a comprehensive revitalization planning study of the East Atlantic Ave corridor that examines multimodal options, traffic calming effects, infrastructure upgrades and public access.", "AMT_WEB": "$60,000", "TITLE": "East Atlantic Avenue Corridor Multi-Use Improvement Study", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16neDRDdEtBRkNqVTg\/view?usp=drivesdk", "LAT": -75.07064569000001, "LONG": 39.88801402, "LEAD_MUN": "Audubon" }, "geometry": { "type": "Point", "coordinates": [ -75.07064569, 39.88801402 ] } },
        { "type": "Feature", "properties": { "FID": 207, "YR": 2015, "ID": 403, "PROJ_DESC": "Development of a Linear Park Concept Plan adjacent to the business park on First Avenue. Connectivity, mobility and open space will be addressed.", "AMT_WEB": "$88,000", "TITLE": "First Avenue Linear Park Concept Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nSXNGQjZlUWRnazg\/view?usp=drivesdk", "LAT": -75.37915826, "LONG": 40.09030244, "LEAD_MUN": "Upper Merion" }, "geometry": { "type": "Point", "coordinates": [ -75.37915826, 40.09030244 ] } },
        { "type": "Feature", "properties": { "FID": 208, "YR": 2015, "ID": 369, "PROJ_DESC": "Perform an updated analysis of three identified redevelopment areas within Clifton Heights Borough, as identified in the 2008 Main Street Master Plan and the Baltimore Avenue Corridor Revitalization Plan.", "AMT_WEB": "$20,000", "TITLE": "Clifton Heights Market Study", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nblYxOUF1aERpZmM\/view?usp=drivesdk", "LAT": -75.29580557, "LONG": 39.93015513, "LEAD_MUN": "Clifton Heights" }, "geometry": { "type": "Point", "coordinates": [ -75.29580557, 39.93015513 ] } },
        { "type": "Feature", "properties": { "FID": 209, "YR": 2015, "ID": 416, "PROJ_DESC": "Conduct an updated Transit Hub Feasibility Analysis for the City of Woodbury that includes existing physical, market, redevelopment and transportation conditions, a market analysis to determine appropriate scale and mix of development uses,", "PROJ_DESC2": "a fiscal analysis and public outreach.", "AMT_WEB": "$75,000", "TITLE": "Transportation Hub Feasibility Study\/Analysis", "WEBLINK": "na", "LAT": -75.15239898, "LONG": 39.83785499, "LEAD_MUN": "Woodbury" }, "geometry": { "type": "Point", "coordinates": [ -75.15239898, 39.83785499 ] } },
        { "type": "Feature", "properties": { "FID": 210, "YR": 2015, "ID": 414, "PROJ_DESC": "Develop streetscape and frontage standards to guide future development along the Blackhorse Pike, conforming to the adjacent plan developed for Blackwood West.", "AMT_WEB": "$64,000", "TITLE": "Blackhorse Pike Corridor Wayfinding Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nU2w2YVpuMVpIM2M\/view?usp=drivesdk", "LAT": -75.03630565, "LONG": 39.79241296, "LEAD_MUN": "Gloucester Township" }, "geometry": { "type": "Point", "coordinates": [ -75.03630565, 39.79241296 ] } },
        { "type": "Feature", "properties": { "FID": 211, "YR": 2015, "ID": 382, "PROJ_DESC": "TCDI funds will enable the borough to develop a borough-wide wayfinding system plan for visitors to locate Media’s unique restaurants, businesses and cultural offerings.", "AMT_WEB": "$40,000", "TITLE": "Wayfinding Signage Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nRFlTel9qWVdGWkE\/view?usp=drivesdk", "LAT": -75.38897621, "LONG": 39.91975519, "LEAD_MUN": "Media Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.38897621, 39.91975519 ] } },
        { "type": "Feature", "properties": { "FID": 212, "YR": 2015, "ID": 366, "PROJ_DESC": "Update the Subdivision and Land Development Ordinance (SALDO) to adequately address new growth and infill development within the context of an historic, walkable downtown.", "AMT_WEB": "$20,000", "TITLE": "SALDO Update", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16ncUpSSUl0OUs0ODQ\/view?usp=drivesdk", "LAT": -75.52006337, "LONG": 40.13588935, "LEAD_MUN": "Phoenixville" }, "geometry": { "type": "Point", "coordinates": [ -75.52006337, 40.13588935 ] } },
        { "type": "Feature", "properties": { "FID": 213, "YR": 2015, "ID": 367, "PROJ_DESC": "Schuylkill Township is located adjacent to the Borough of Phoenixville, which is currently undergoing rebirth of businesses and retail.  This project will study the feasibility of connecting the Township to downtown Phoenixville with a sidewalk", "PROJ_DESC2": "system plan.", "AMT_WEB": "$60,000", "TITLE": "Schuylkill Sidwalk System", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nYktraVA0SFl4V0E\/view?usp=drivesdk", "LAT": -75.49823988, "LONG": 40.10861224, "LEAD_MUN": "Schuylkill Township" }, "geometry": { "type": "Point", "coordinates": [ -75.49823988, 40.10861224 ] } },
        { "type": "Feature", "properties": { "FID": 214, "YR": 2015, "ID": 364, "PROJ_DESC": "Prepare a coordinated long-term land use and transportation strategy for all transportation modes between West Sadsbury Township (Lancaster\/Chester County border) and Caln Township (US 322).", "AMT_WEB": "$75,000", "TITLE": "Route 30 Multi-Modal Transportation Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nNTJrSGZZSWNTTzQ\/view?usp=drivesdk", "LAT": -75.87616809, "LONG": 39.99992258, "LEAD_MUN": "Caln Township" }, "geometry": { "type": "Point", "coordinates": [ -75.87616809, 39.99992258 ] } },
        { "type": "Feature", "properties": { "FID": 215, "YR": 2015, "ID": 368, "PROJ_DESC": "Update Aston’s 2005 Comprehensive Plan (with a special emphasis on the transportation plan components) with new overlay zoning ordinances for its two major commercial arterials, Pennell Road and Concord Pike.", "AMT_WEB": "$88,000", "TITLE": "Comprehensive Plan Update, Ordinance Revisions", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nMEJCMkVJM3V6em8\/view?usp=drivesdk", "LAT": -75.43481157, "LONG": 39.87182012, "LEAD_MUN": "Aston Township" }, "geometry": { "type": "Point", "coordinates": [ -75.43481157, 39.87182012 ] } },
        { "type": "Feature", "properties": { "FID": 216, "YR": 2015, "ID": 409, "PROJ_DESC": "Facilitate a visioning process for the future reuse of the Ocean Spray properties.  The process will include a feasibility analysis based on visioning exercises that include community engagement and outreach and an analysis of existing conditions.", "AMT_WEB": "$100,000", "TITLE": "Ocean Spray Redevelopment and Linkage Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nYzAxRU9tRi0tLXc\/view?usp=drivesdk", "LAT": -74.70869107, "LONG": 40.14927396, "LEAD_MUN": "Bordentown City" }, "geometry": { "type": "Point", "coordinates": [ -74.70869107, 40.14927396 ] } },
        { "type": "Feature", "properties": { "FID": 217, "YR": 2015, "ID": 461, "PROJ_DESC": "The Township adopted a TDR ordinance in 2008, which enabled them to secure a State endorsed, “Smart Growth Center” designation along Route 322. TCDI funds will be used to prepare a comprehensive master plan reexamination that amends and", "PROJ_DESC2": "updates the land use and transportation element of the TDR Plan.", "AMT_WEB": "$100,000", "TITLE": "Unified Land Use and Transportation Master Plan", "WEBLINK": "na", "LAT": -75.31700578, "LONG": 39.74003291, "LEAD_MUN": "Woolwich Township" }, "geometry": { "type": "Point", "coordinates": [ -75.31700578, 39.74003291 ] } },
        { "type": "Feature", "properties": { "FID": 218, "YR": 2015, "ID": 363, "PROJ_DESC": "This study will include a detailed investigation of land use, multi use transportation options, and economic development potential to determine if a Main Street type corridor is feasible.", "AMT_WEB": "$80,000", "TITLE": "Main Street", "WEBLINK": "na", "LAT": -75.18062752, "LONG": 40.29811654, "LEAD_MUN": "New Britain Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.18062752, 40.29811654 ] } },
        { "type": "Feature", "properties": { "FID": 219, "YR": 2015, "ID": 361, "PROJ_DESC": "This study is a multi-municipal effort that includes the Townships of Doylestown, Buckingham, and Plumstead, as well as Doylestown Borough.  TCDI funds will be used to investigate the following (1) land use and zoning, (2) economic development", "PROJ_DESC2": "conidtions, (3)streetscape and corridor improvements, and (4) transportation alternatives.  Underutilized sites will be identified and potential options or uses for their optimization will be explored, with the purpose of developing the strongest", "PROJ_DESC3": "business profile", "AMT_WEB": "$80,000", "TITLE": "Cross Keys Planning and Transportation Study", "WEBLINK": "na", "LAT": -75.09668156, "LONG": 40.33837249, "LEAD_MUN": "Bucks County" }, "geometry": { "type": "Point", "coordinates": [ -75.09668156, 40.33837249 ] } },
        { "type": "Feature", "properties": { "FID": 220, "YR": 2015, "ID": 411, "PROJ_DESC": "Create a Complete Streets policy for the entire Township that will assist in expanding residential and commercial development within a designated center, Browns Mills, as well as implement the recently adopted form-based code.", "AMT_WEB": "$50,000", "TITLE": "Complete Streets Policy and Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nbmt1eWtSeHBSNjA\/view?usp=drivesdk", "LAT": -74.5999675, "LONG": 39.95618433, "LEAD_MUN": "Pemberton" }, "geometry": { "type": "Point", "coordinates": [ -74.5999675, 39.95618433 ] } },
        { "type": "Feature", "properties": { "FID": 221, "YR": 2015, "ID": 410, "PROJ_DESC": "This project proposes to study on and off road trail routing alternatives for a 5 mile segment of the Rancocas Creek Greenway (part of the greater Philadelphia region's Circuit trail network).  It will examine solutions to provide safer pedestrian", "PROJ_DESC2": "crosssings along U.S. Route 130.", "AMT_WEB": "$95,000", "TITLE": "Rancocas Creek Greenway, Amico Island Park", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nRlBKNlFpcWtZWVk\/view?usp=drivesdk", "LAT": -74.92252419, "LONG": 40.02766519, "LEAD_MUN": "Burlington County" }, "geometry": { "type": "Point", "coordinates": [ -74.92252419, 40.02766519 ] } },
        { "type": "Feature", "properties": { "FID": 222, "YR": 2015, "ID": 365, "PROJ_DESC": "This study will address anticipated parking issues in the downtown.", "AMT_WEB": "$20,000", "TITLE": "Downtown Parking Study", "WEBLINK": "na", "LAT": -75.81982339, "LONG": 39.98502887, "LEAD_MUN": "Coatesville" }, "geometry": { "type": "Point", "coordinates": [ -75.81982339, 39.98502887 ] } },
        { "type": "Feature", "properties": { "FID": 223, "YR": 2015, "ID": 406, "PROJ_DESC": "Enhance connectivity and pedestrian safety from 30th Street Station to the medical complex (PENN and CHOP).  This study will focus on developing recommendations for six intersections and transit options.", "AMT_WEB": "$75,000", "TITLE": "University City Access Study", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nTU1CcDRHM3hMN0E\/view?usp=drivesdk", "LAT": -75.19121408, "LONG": 39.95052005, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.19121408, 39.95052005 ] } },
        { "type": "Feature", "properties": { "FID": 224, "YR": 2015, "ID": 421, "PROJ_DESC": "Develop the county wide land use and circulation element of the County master Plan.  A visioning process will be included to ensure community participation.", "AMT_WEB": "$125,000", "TITLE": "Master Plan for the New Millennium-Unified Land Use and Circulation Element", "WEBLINK": "na", "LAT": -75.14107871, "LONG": 39.71706878, "LEAD_MUN": "Gloucester County" }, "geometry": { "type": "Point", "coordinates": [ -75.14107871, 39.71706878 ] } },
        { "type": "Feature", "properties": { "FID": 225, "YR": 2015, "ID": 381, "PROJ_DESC": "Technical assistance will be provided to targeted municipalities to develop the following: an energy use baseline, facility level energy assessments, and opportunities for reducing energy use in municipal buildings and facilities.", "AMT_WEB": "$76,000", "TITLE": "Technical Asssistance for Energy Efficiency in Local Government Operations", "WEBLINK": "na", "LAT": -75.39877209, "LONG": 39.91659822, "LEAD_MUN": "Delaware County Planning Dept." }, "geometry": { "type": "Point", "coordinates": [ -75.39877209, 39.91659822 ] } },
        { "type": "Feature", "properties": { "FID": 226, "YR": 2015, "ID": 402, "PROJ_DESC": "Montgomery County Planning Commission has recently produced model ordinances for walkable development, created a walkability score for neighborhoods, mapped all sidewalks in the county, and conducted a walkability audit in Collegeville.", "PROJ_DESC2": "TCDI funds will be used to create a county-wide walkability plan with four targeted walkability audits.", "AMT_WEB": "$50,000", "TITLE": "Walkability Plan", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nUmZtMTBEY2JRZUk\/view?usp=drivesdk", "LAT": -75.36733313000001, "LONG": 40.21084201, "LEAD_MUN": "Montgomery County" }, "geometry": { "type": "Point", "coordinates": [ -75.36733313, 40.21084201 ] } },
        { "type": "Feature", "properties": { "FID": 227, "YR": 2015, "ID": 405, "PROJ_DESC": "This project will help achieve a higher level of efficiency and safety in accord with the City’s Complete Streets policy.  TCDI funds will be used to study five intersections that have been chosen through the Philadelphia2035 district planning", "PROJ_DESC2": "process.", "AMT_WEB": "$100,000", "TITLE": "Complete Streets Improvements Plan", "WEBLINK": "na", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } },
        { "type": "Feature", "properties": { "FID": 228, "YR": 2015, "ID": 407, "PROJ_DESC": "The Philadelphia Trail Master Plan identifies more than 100 miles of proposed trails, including those that will close gaps in the existing trail network and provide trail and green amenities to underserved neighborhoods.  TCDI funds will examine", "PROJ_DESC2": "three identified projects for potential alignment alternatives, property ownership, development potential, and best management practices for safe trail operations.", "AMT_WEB": "$100,000", "TITLE": "Rails and Trails: Trail Feasibility in Philadelphia", "WEBLINK": "https:\/\/drive.google.com\/a\/dvrpc.org\/file\/d\/0BzX5TLpz-16nUW5oVXZlWUpEYTQ\/view?usp=drivesdk", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } }
    ]
}
const currentDataSet = {
    "type": "FeatureCollection",
    "name": "tcdi_centroids",
    "features": [
        { "type": "Feature", "properties": { "FID": 229, "YR": 2017, "ID": 501, "PROJ_DESC": "The River Route Circulation Plan will focus on updating the 1997 circulation and transportation component of the River Route Master Plan. The plan will identify safety, functional, and operational problems and provide investment strategies to link", "PROJ_DESC2": "transportation improvements with economic development opportunities.", "AMT_WEB": "$175,000", "TITLE": "River Route Circulation Plan", "WEBLINK": "na", "LAT": -74.89376865, "LONG": 40.04729549, "LEAD_MUN": "Burlington County Planning" }, "geometry": { "type": "Point", "coordinates": [ -74.89376865, 40.04729549 ] } },
        { "type": "Feature", "properties": { "FID": 230, "YR": 2017, "ID": 902, "PROJ_DESC": "An in-depth land use and buildout analysis will be conducted for the communities of Beverly, Delanco, and Edgewater Park to assess the future traffic volumes for the interchange at location 32 along U.S. Route 130.", "AMT_WEB": "$100,000", "TITLE": "Conceptual Design Plan to Route 130 Intersections", "WEBLINK": "na", "LAT": -74.92929221, "LONG": 40.05294662, "LEAD_MUN": "Burlington County Planning (Multi-Municipal)" }, "geometry": { "type": "Point", "coordinates": [ -74.92929221, 40.05294662 ] } },
        { "type": "Feature", "properties": { "FID": 231, "YR": 2017, "ID": 503, "PROJ_DESC": "The Township will develop a vision for the area adjacent to the PATCO Woodcrest Station that supports transit-oriented development and", "PROJ_DESC2": "related planning practices.", "AMT_WEB": "$60,000", "TITLE": "Woodcrest Station Transit-Oriented Development (TOD) Plan", "WEBLINK": "na", "LAT": -74.99461206, "LONG": 39.90340864, "LEAD_MUN": "Cherry Hill" }, "geometry": { "type": "Point", "coordinates": [ -74.99461206, 39.90340864 ] } },
        { "type": "Feature", "properties": { "FID": 232, "YR": 2017, "ID": 504, "PROJ_DESC": "A new interior and exterior redesign\/concept plan will be developed for the Walter Rand Transportation Center in order to better leverage existing transportation infrastructure as a resource to transform", "PROJ_DESC2": "a derelict facility into a world class transportation center.", "AMT_WEB": "$100,000", "TITLE": "Walter Rand Market Feasibility & Station Redesign", "WEBLINK": "na", "LAT": -75.10756319, "LONG": 39.93618305, "LEAD_MUN": "Camden County" }, "geometry": { "type": "Point", "coordinates": [ -75.10756319, 39.93618305 ] } },
        { "type": "Feature", "properties": { "FID": 233, "YR": 2017, "ID": 505, "PROJ_DESC": "This study will develop a balance between travel modes, parking needs, and the future economic development in Princeton’s downtown.", "PROJ_DESC2": "A parking demand baseline will be developed with short and long-term recommendations to accommodate future downtown residential development parking needs.", "AMT_WEB": "$65,000", "TITLE": "Princeton Parking: Inventory, Analysis & Recommendations", "WEBLINK": "na", "LAT": -74.66932503, "LONG": 40.3562264, "LEAD_MUN": "Princeton" }, "geometry": { "type": "Point", "coordinates": [ -74.66932503, 40.3562264 ] } },
        { "type": "Feature", "properties": { "FID": 234, "YR": 2017, "ID": 506, "PROJ_DESC": "The Downtown Trenton Waterfront Reclamation Redevelopment Project (Route 29 realignment) is a shared vision to reconnect the City to the waterfront.", "PROJ_DESC2": "TCDI funding will be used to identify case studies, review FEMA regulations, and develop a regional market analysis, and promotional materials.", "AMT_WEB": "$100,000", "TITLE": "Waterfront Reclamation and Redevelopment Project", "WEBLINK": "na", "LAT": -74.76413829000001, "LONG": 40.22368004, "LEAD_MUN": "Trenton" }, "geometry": { "type": "Point", "coordinates": [ -74.76413829, 40.22368004 ] } },
        { "type": "Feature", "properties": { "FID": 235, "YR": 2017, "ID": 481, "PROJ_DESC": "In an effort to address the investment in the I-95–PA turnpike connection and Route 13, an economic development study will be performed to assess the impact of the transportation improvements on economic conditions and adjoining land uses and zoning.", "AMT_WEB": "$80,000", "TITLE": "Economic Development Analysis", "WEBLINK": "na", "LAT": -74.86671034, "LONG": 40.12158498, "LEAD_MUN": "Bucks County Planning Department" }, "geometry": { "type": "Point", "coordinates": [ -74.86671034, 40.12158498 ] } },
        { "type": "Feature", "properties": { "FID": 236, "YR": 2017, "ID": 483, "PROJ_DESC": "Design concepts will be developed to promote Chester County as a tourist destination and provide for the ease and safety of visitors traveling unfamiliar winding roads through the Brandywine region.", "AMT_WEB": "$40,000", "TITLE": "Brandywine Valley Wayfinding Signage Plan", "WEBLINK": "na", "LAT": -75.7484118, "LONG": 39.97317085, "LEAD_MUN": "Chester County Planning Department" }, "geometry": { "type": "Point", "coordinates": [ -75.7484118, 39.97317085 ] } },
        { "type": "Feature", "properties": { "FID": 237, "YR": 2017, "ID": 482, "PROJ_DESC": "This multi-municipal study will include Phoenixville Borough, Schuylkill Township, East Pikeland Township, Charlestown Township, West Vincent Township, and Upper Providence Township.", "PROJ_DESC2": "Chester County staff will develop a multi-modal plan in response to the new residential development and increase in single occupancy vehicles on the road network in the Phoenixville region.", "AMT_WEB": "$52,000", "TITLE": "Phoenixville Region Multi-Modal Transportation Plan", "WEBLINK": "na", "LAT": -75.55407227000001, "LONG": 40.12795974, "LEAD_MUN": "Chester County Planning Department" }, "geometry": { "type": "Point", "coordinates": [ -75.55407227, 40.12795974 ] } },
        { "type": "Feature", "properties": { "FID": 238, "YR": 2017, "ID": 484, "PROJ_DESC": "A Master Plan will be produced that provides a framework for circulation and land use along the Paoli Pike corridor. It will focus on developing a Paoli Pike Promenade that is multi-modal, focusing on pedestrian safety.", "AMT_WEB": "$52,500", "TITLE": "Paoli Pike Corridor Master Plan", "WEBLINK": "na", "LAT": -75.54783375, "LONG": 39.99346891, "LEAD_MUN": "East Goshen Township" }, "geometry": { "type": "Point", "coordinates": [ -75.54783375, 39.99346891 ] } },
        { "type": "Feature", "properties": { "FID": 239, "YR": 2017, "ID": 485, "PROJ_DESC": "A coordinated transportation and land use study will identify alternative modes along Route 30 to address the problems of traffic congestion and its negative impacts on surrounding residential neighborhoods.", "AMT_WEB": "$75,000", "TITLE": "Route 30 Corridor Study", "WEBLINK": "na", "LAT": -75.55470729, "LONG": 40.04736992, "LEAD_MUN": "East Whiteland Township" }, "geometry": { "type": "Point", "coordinates": [ -75.55470729, 40.04736992 ] } },
        { "type": "Feature", "properties": { "FID": 240, "YR": 2017, "ID": 486, "PROJ_DESC": "This study will analyze the existing parking demands and infrastructure in the downtown business corridor. The study will examine existing conditions, the needs of local business owners, downtown residents, and visitors", "PROJ_DESC2": "as well as project future parking needs for additional residential development.", "AMT_WEB": "$34,000", "TITLE": "Downtown Parking Study", "WEBLINK": "na", "LAT": -75.52006337, "LONG": 40.13588935, "LEAD_MUN": "Phoenixville" }, "geometry": { "type": "Point", "coordinates": [ -75.52006337, 40.13588935 ] } },
        { "type": "Feature", "properties": { "FID": 241, "YR": 2017, "ID": 487, "PROJ_DESC": "This study will address access issues to the Exton Train Station as well as examine the potential for transit-oriented development.", "AMT_WEB": "$25,000", "TITLE": "Pottstown Pike Congestion Mitigation Feasibility Study", "WEBLINK": "na", "LAT": -75.62389614, "LONG": 40.0227008, "LEAD_MUN": "West Whiteland Township" }, "geometry": { "type": "Point", "coordinates": [ -75.62389614, 40.0227008 ] } },
        { "type": "Feature", "properties": { "FID": 242, "YR": 2017, "ID": 488, "PROJ_DESC": "To address the loss of residential and commercial tenancy over the past decade, the County Planning Department will undertake a visioning process to help stimulate reinvestment in Delaware County’s Central Places.", "PROJ_DESC2": "The process will result in three separate vision plans.", "AMT_WEB": "$80,000", "TITLE": "Downtown Awakening: Central Places Visioning", "WEBLINK": "na", "LAT": -75.39877209, "LONG": 39.91659822, "LEAD_MUN": "Delaware County Planning Department" }, "geometry": { "type": "Point", "coordinates": [ -75.39877209, 39.91659822 ] } },
        { "type": "Feature", "properties": { "FID": 243, "YR": 2017, "ID": 489, "PROJ_DESC": "In response to trolley investments in the downtown, an updated economic development strategy will be developed that focuses on continued residential and commercial business growth in the central business district.", "AMT_WEB": "$56,250", "TITLE": "Updated Economic Development Strategy", "WEBLINK": "na", "LAT": -75.38897621, "LONG": 39.91975519, "LEAD_MUN": "Media Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.38897621, 39.91975519 ] } },
        { "type": "Feature", "properties": { "FID": 244, "YR": 2017, "ID": 490, "PROJ_DESC": "This study will address high volumes of traffic through the central business district and residential neighborhoods. It will analyze possible transportation solutions such as traffic calming and streetscape enhancements", "PROJ_DESC2": "to stimulate economic development.", "AMT_WEB": "$36,000", "TITLE": "Morton Connect", "WEBLINK": "na", "LAT": -75.32678187, "LONG": 39.9115795, "LEAD_MUN": "Morton Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.32678187, 39.9115795 ] } },
        { "type": "Feature", "properties": { "FID": 245, "YR": 2017, "ID": 491, "PROJ_DESC": "This project will include a traffic study to identify vehicular and pedestrian circulation through the Garrett Road and Byword Avenue area. It will identify potential placemaking enhancements to modernize", "PROJ_DESC2": "and increase accessibility of the SEPTA 101 and 102 lines.", "AMT_WEB": "$71,250", "TITLE": "Multi-Modal Modernization of the Garrett Road Corridor", "WEBLINK": "na", "LAT": -75.28907454, "LONG": 39.94902642, "LEAD_MUN": "Upper Darby Township" }, "geometry": { "type": "Point", "coordinates": [ -75.28907454, 39.94902642 ] } },
        { "type": "Feature", "properties": { "FID": 246, "YR": 2017, "ID": 495, "PROJ_DESC": "This project is part of an ongoing effort to enhance bike and pedestrian mobility through the county. This plan will include design improvements and key policies for bicycle safety.", "AMT_WEB": "$30,000", "TITLE": "Bike Montco Plan Development", "WEBLINK": "na", "LAT": -75.36733313000001, "LONG": 40.21084201, "LEAD_MUN": "Montgomery County Planning Commission" }, "geometry": { "type": "Point", "coordinates": [ -75.36733313, 40.21084201 ] } },
        { "type": "Feature", "properties": { "FID": 247, "YR": 2017, "ID": 492, "PROJ_DESC": "This study strives to maximize the capacity of the Township’s transportation infrastructure by increasing transit ridership and encouraging increased pedestrian and bicycle mobility throughout, specifically to the train station.", "AMT_WEB": "$75,000", "TITLE": "Walk Park Train", "WEBLINK": "na", "LAT": -75.11456772, "LONG": 40.11080415, "LEAD_MUN": "Abington Township" }, "geometry": { "type": "Point", "coordinates": [ -75.11456772, 40.11080415 ] } },
        { "type": "Feature", "properties": { "FID": 248, "YR": 2017, "ID": 493, "PROJ_DESC": "This study will identify a preferred alignment for a multi-use recreation trail from the Madison Lot (SEPTA station) to the Lansdale\/Hatfield municipal border.", "PROJ_DESC2": "The trail will enhance walkability in Lansdale and connect directly to the downtown business corridor.", "AMT_WEB": "$28,000", "TITLE": "Liberty Bell Trail Alignment Study", "WEBLINK": "na", "LAT": -75.28119889, "LONG": 40.24164092, "LEAD_MUN": "Lansdale Borough" }, "geometry": { "type": "Point", "coordinates": [ -75.28119889, 40.24164092 ] } },
        { "type": "Feature", "properties": { "FID": 249, "YR": 2017, "ID": 494, "PROJ_DESC": "A connectivity plan will be developed that analyzes the existing transportation network and provides recommendations for accommodating future residential development.", "AMT_WEB": "$80,000", "TITLE": "Ridge Pike West Corridor Study", "WEBLINK": "na", "LAT": -75.42676927, "LONG": 40.14850795, "LEAD_MUN": "Lower Providence" }, "geometry": { "type": "Point", "coordinates": [ -75.42676927, 40.14850795 ] } },
        { "type": "Feature", "properties": { "FID": 250, "YR": 2017, "ID": 496, "PROJ_DESC": "The TDM plan will address current commuting patterns of the park’s current employees, barriers to alternative modes of transportation, and future residential and commercial growth", "AMT_WEB": "$75,000", "TITLE": "Transportation Demand Plan (TDM) Plan for the Ft. Washington Office Park", "WEBLINK": "na", "LAT": -75.1812935, "LONG": 40.15017338, "LEAD_MUN": "Upper Dublin Township" }, "geometry": { "type": "Point", "coordinates": [ -75.1812935, 40.15017338 ] } },
        { "type": "Feature", "properties": { "FID": 251, "YR": 2017, "ID": 498, "PROJ_DESC": "This study will analyze peer city sidewalk repair strategies and provide recommendations for Philadelphia-specific repair program and prioritization methodology.", "PROJ_DESC2": "The menu of implementation options will enable the City government to evaluate solutions to equitably maintain sidewalks.", "AMT_WEB": "$100,000", "TITLE": "Where the Sidewalk Gaps: A Program for Prioritizing Repairs", "WEBLINK": "na", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Office of Transportation & Infrastructure Systems" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } },
        { "type": "Feature", "properties": { "FID": 252, "YR": 2017, "ID": 499, "PROJ_DESC": "The City of Philadelphia released its Complete Streets Handbook which articulated the City’s multi-modal standards and priorities.", "PROJ_DESC2": "The proposed calculator will provide a tool to predict the impact of future development on transportation priorities and analyze the social and financial impact complete streets provides.", "AMT_WEB": "$80,000", "TITLE": "Complete Streets Calculator", "WEBLINK": "na", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Office of Transportation and Infrastructure Systems" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } },
        { "type": "Feature", "properties": { "FID": 253, "YR": 2017, "ID": 500, "PROJ_DESC": "TCDI funding will enable the City of Philadelphia to engage its research community to develop innovative, smart thinking around Vision Zero and other related policies.", "PROJ_DESC2": "Outreach will be conducted to neighboring cities on best practices and a report will be produced with recommended policies for Philadelphia.", "AMT_WEB": "$30,000", "TITLE": "Critical Matchmaking between Vision Zero Research and Practice", "WEBLINK": "na", "LAT": -75.13417344, "LONG": 40.00765503, "LEAD_MUN": "Department of Streets, City of Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.13417344, 40.00765503 ] } },
        { "type": "Feature", "properties": { "FID": 254, "YR": 2017, "ID": 497, "PROJ_DESC": "This study will further the recommendations from the Lower Northwest District Plan Focus Area and examine immediate and long-term improvements to accommodate new development and increase transportation access and safety.", "AMT_WEB": "$100,000", "TITLE": "Wissahickon Gateway", "WEBLINK": "na", "LAT": -75.22189866, "LONG": 40.04325709, "LEAD_MUN": "Philadelphia City Planning Commission" }, "geometry": { "type": "Point", "coordinates": [ -75.22189866, 40.04325709 ] } }
    ]
}

// Accordion functionality
const accordion = document.querySelectorAll('.accordion')
for(var i = 0; i < accordion.length; i++){
    accordion[i].onclick = function(){
        // show/hide the accordions on click
        this.classList.toggle('active')

        // toggle the aria-expanded attribute of the accordion button
        let ariaExpandedBool = this.getAttribute('aria-expanded')
        ariaExpandedBool === 'false' ? ariaExpandedBool = 'true' : ariaExpandedBool = 'false'
        this.setAttribute('aria-expanded', ariaExpandedBool)

        // toggle the aria-hidden attribute of the accordion panel
        const panel = this.nextElementSibling
        let ariaHiddenBool = panel.getAttribute('aria-hidden')
        ariaHiddenBool === 'false' ? ariaHiddenBool = 'true' : ariaHiddenBool = 'false'
        panel.setAttribute('aria-hidden', ariaHiddenBool)

        // show/hide the panel on click
        if(panel.style.maxHeight) panel.style.maxHeight = null
        else panel.style.maxHeight = panel.scrollHeight + 'px'
    }
}

const populateProjectDetails = (dataset, tableName) => {
    const table = document.querySelector('#'+tableName)
    const year = dataset.features[0].properties.YR

    // fill out the awards header
    const awardsHeader = document.querySelector('h2.'+tableName)
    awardsHeader.textContent = year + ' TCDI AWARDS'

    // fill out the accordion header where applicable
    if(tableName != 'currentDataSet'){
        const accordionButton = document.querySelector('.'+tableName)
        accordionButton.textContent = year + ' Projects'
    }

    dataset.features.forEach(project => {
        const newRow = table.insertRow()
        const municipalityColumn = newRow.insertCell()
        const titleColumn = newRow.insertCell()
        const amountColumn = newRow.insertCell()

        const municipality = project.properties.LEAD_MUN
        const title = project.properties.TITLE
        const link = project.properties.WEBLINK
        const amount = project.properties.AMT_WEB

        municipalityColumn.textContent = municipality
        titleColumn.innerHTML = link === 'na' ? title : `<a href="${link}" rel="external">${title}</a>`
        amountColumn.textContent = amount
        amountColumn.style.textAlign = 'right'
    })
}

populateProjectDetails(currentDataSet, 'currentDataSet')
populateProjectDetails(previousDataSet, 'previousDataSet')
populateProjectDetails(secondPreviousDataSet, 'secondPreviousDataSet')
populateProjectDetails(thirdPreviousDataSet, 'thirdPreviousDataSet')

mapboxgl.accessToken = 'pk.eyJ1IjoibW1vbHRhIiwiYSI6ImNqZDBkMDZhYjJ6YzczNHJ4cno5eTcydnMifQ.RJNJ7s7hBfrJITOBZBdcOA'

const maxRadius = 25
const minRadius = 5

const stylesheet = {
  "version": 8,
  "sources": {
    "counties": {
      "type": "vector",
      // TODO: migrate to SSL domain from Mike
      "url": "https://dvrpc-freight.michaelruane.com/dvrpc_boundaries.json"
    }
  },
  "layers": [
    {"id": "county-fill",
      "type": "fill",
      "source": "counties",
      "source-layer": "county",
      "layout": {},
      "paint": {
          "fill-color": "#B6C1C6",
          "fill-opacity": 1
      },
      "filter": [
                "==",
                "DVRPC_REG",
                "Yes"
        ],
    },
    {
        "id": "municipality-outline",
        "type": "line",
        "source": "counties",
        "source-layer": "municipalities",
        "paint": {
            'line-width': 0.5,
            'line-color': '#efefef'
        }
    },
    {
        "id": "county-outline",
        "type": "line",
        "source": "counties",
        "source-layer": "county",
        "paint": {
            'line-width': 2.5,
            'line-color': '#fff'
        },
        "filter": [
                "==",
                "DVRPC_REG",
                "Yes"
            ]
    }
  ]
} 

const map = new mapboxgl.Map({
    container: 'map',
    style: stylesheet,
    attributionControl: false,
    center: [-75.2273, 40.071],
    zoom: 8.82
});

map.fitBounds([[-76.09405517578125, 39.49211914385648],[-74.32525634765625,40.614734298694216]]);

// convert WEB_AMT to numeric value so mapboxGL can create graduated circles
currentDataSet.features.forEach(project => project.properties.AMOUNT = parseInt(project.properties.AMT_WEB.slice(1)))

const award_layer = id => {
    return {
        'id': id,
        'type': 'circle',
        'source': id,
        'paint': {
            'circle-radius': {
                property: 'AMOUNT',
                type: 'exponential',
                stops: [[25, minRadius], [175, maxRadius]]
            },
            'circle-color': '#6fb8b9',
            'circle-opacity': 0.7,
            'circle-stroke-width': 1.25,
            'circle-stroke-color': '#fff',
            'circle-stroke-opacity': 0.7
        },
    }
}

const award_hover = (id, source) => {
    return {
        'id': id,
        'type': 'circle',
        'source': source,
        'paint': {
            'circle-radius': {
                property: 'AMOUNT',
                type: 'exponential',
                stops: [[25, minRadius], [175, maxRadius]]
            },
            'circle-color': '#6fb8b9',
            'circle-opacity': 1,
            'circle-stroke-width': 1.5,
            'circle-stroke-color': '#fff',
            'circle-stroke-opacity': 1
        },
        'filter': [
            '==',
            'FID',
            ''
        ]
    }
}

const popupDetails = e => {
    new mapboxgl.Popup({
            closebutton: true,
            closeOnClick: true
        }).setLngLat(e.features[0].geometry.coordinates)
        .setHTML(`<strong>${e.features[0].properties.TITLE}</strong><br />${e.features[0].properties.PROJ_DESC}..<br /><em>Award Amount: </em>${e.features[0].properties.AMT_WEB}`)
        .addTo(map)
}

const legend = document.querySelector('#legend-labels')
const legendSizes = [{size: 25, class: 'large'}, {size: 15, class: 'medium'}, {size: 5, class: 'small'}]

// @to-do need to automate calculation of max and min awards which could be used in this function current data is 25 and 175
const rateOfChange = (maxRadius - minRadius) / (175 - 25);
const radiusAtZero = maxRadius - (rateOfChange * 175);

const roundfive = num => (num % 5) >= 2.5 ? parseInt(num / 5) * 5 + 5 : parseInt(num / 5) * 5

const awardSize = circleRadius => {
    let awardVal = (circleRadius - radiusAtZero) / rateOfChange
    let label = '$' + roundfive(awardVal) + 'k'
    
    return label
}

legendSizes.forEach(circle => {
    let labelText = awardSize(circle.size);
    legend.insertAdjacentHTML('beforeend', `<p class="leg-label ${circle.class}">${labelText}</p>`)
})

map.on('load', function(){
    map.addSource('current-year-awards', {
        type: 'geojson',
        data: currentDataSet
    })
    map.addLayer(award_layer('current-year-awards'))
    map.addLayer(award_hover('current-year-hover', 'current-year-awards'))

    map.on('click', 'current-year-awards', e => popupDetails(e))
    map.on('mousemove', 'current-year-awards', e => {
        map.getCanvas().style.cursor = 'pointer'
        map.setFilter('current-year-hover', ['==', 'FID', e.features[0].properties['FID']])})
    map.on('mouseleave', 'current-year-awards', e => {
        map.getCanvas().style.cursor = ''
        map.setFilter('current-year-hover', ['==', 'FID', ''])})
})